### ISSUE TITLE
Chapter 2 Exercise 4.1 (k)

### ISSUE THREAD

**Issue by Vedant-Sharma-39** [shejialuo/database-systems-complete-book-solutions#17]
![0858](https://github.com/shejialuo/database-systems-complete-book-solutions/assets/74167738/3f404345-c76f-4367-a94d-5d6d0eb25977)

I would like to confirm the correctness of this statement. Please check if there is a flaw in my understanding.

R6 contains the cartesian product such that maker has at least three different models. If a given maker has 4 different models than this formulation will incorrectly include the tuples where model4 equates one of model, model2 and model3. I think we should similarly find the cartesian product such that maker has at least four different models and then take difference.

**Comment by shejialuo** [comment]
Thanks for your issue, I am a little busy these days, will reply to you later!

**Comment by shejialuo** [comment]
> If a given maker has 4 different models than this formulation will incorrectly include the tuples where model4 equates one of model, model2 and model3

Yes, that's correct. This answer is not correct.

> I think we should similarly find the cartesian product such that maker has at least four different models and then take difference.

Yes, it's a way to do this. We could do diff, we make the at least four different models to be $R_{8}$. If a tuple is in $R_{7}$ but not int $R_{8}$, we will get the correct result.

Could you please add a PR to solve this problem?

Thanks!

**Comment by Vedant-Sharma-39** [comment]
Added, It's been some time so please check the correction once.
